/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// 환경변수를 사용하여 Supabase 정보를 가져옵니다
// Vercel 배포 시 환경변수에서 값을 읽어옵니다
// Figma Make 환경에서는 기본값을 사용합니다
export const projectId = (typeof import.meta !== 'undefined' && import.meta.env?.VITE_SUPABASE_PROJECT_ID) || "czrylhekwmkdlobeuxuh"
export const publicAnonKey = (typeof import.meta !== 'undefined' && import.meta.env?.VITE_SUPABASE_ANON_KEY) || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6cnlsaGVrd21rZGxvYmV1eHVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUwOTA2NjYsImV4cCI6MjA4MDY2NjY2Nn0.cAciCMZ_xgpaDOsufLB8osENR2ArRz6_qPUomN7GNDU"